name: Pytest unit and functional

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
    - name: Running Pytest on Unit and Functional tests
      run: |
        pytest ./tests -v --disable-pytest-warnings

